/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const _kFontPkg = null;

  static const IconData wallet = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_linear = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open_encrypto = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_enctype = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 = const IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = const IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = const IconData(0xea59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = const IconData(0xeb3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_outlined = const IconData(0xebed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_filled = const IconData(0xebee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_outline = const IconData(0xebef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_filled = const IconData(0xebf0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_outlined = const IconData(0xebf1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_filled = const IconData(0xebf2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_filled = const IconData(0xebf3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_outlined = const IconData(0xebf4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = const IconData(0xebf5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outline = const IconData(0xebf6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_filled = const IconData(0xebf7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = const IconData(0xec39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = const IconData(0xec3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = const IconData(0xec3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = const IconData(0xec3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis = const IconData(0xece9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyelash_open = const IconData(0xefd6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyelash_closed = const IconData(0xefd7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = const IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_down = const IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_mastercard = const IconData(0xf1f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_paypal = const IconData(0xf1f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_stripe = const IconData(0xf1f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_alt = const IconData(0xf283, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = const IconData(0xf342, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
