/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData wallet = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData money = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData stripe = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home_outline = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData floppy = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData search_web = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData down_open = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData down_open_encrypto = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData credit_card = IconData(0xea59, fontFamily: _kFontFam);
  static const IconData briefcase = IconData(0xeb3a, fontFamily: _kFontFam);
  static const IconData chevron_up = IconData(0xec39, fontFamily: _kFontFam);
  static const IconData chevron_down = IconData(0xec3a, fontFamily: _kFontFam);
  static const IconData chevron_left = IconData(0xec3b, fontFamily: _kFontFam);
  static const IconData chevron_right = IconData(0xec3c, fontFamily: _kFontFam);
  static const IconData ellipsis = IconData(0xece9, fontFamily: _kFontFam);
  static const IconData search_ic8 = IconData(0xefd4, fontFamily: _kFontFam);
  static const IconData eyelash_open = IconData(0xefd6, fontFamily: _kFontFam);
  static const IconData eyelash_closed = IconData(0xefd7, fontFamily: _kFontFam);
  static const IconData cash = IconData(0xf0d6, fontFamily: _kFontFam);
  static const IconData angle_down = IconData(0xf107, fontFamily: _kFontFam);
  static const IconData cc_mastercard = IconData(0xf1f1, fontFamily: _kFontFam);
  static const IconData cc_paypal = IconData(0xf1f4, fontFamily: _kFontFam);
  static const IconData cc_stripe = IconData(0xf1f5, fontFamily: _kFontFam);
  static const IconData credit_card_alt = IconData(0xf283, fontFamily: _kFontFam);
  static const IconData paypal = IconData(0xf342, fontFamily: _kFontFam);
}
